
export const RESET = 'tvdl/reset'

export const GET_MEMBER = 'tvdl/getMember'
export const GET_MEMBER_SUCCESS = 'tvdl/getMemberSuccess'
export const GET_MEMBER_FAIL = 'tvdl/getMemberFail'
export const GET_LIST_MEMBER = 'tvdl/getListMember'
export const GET_LIST_MEMBER_SUCCESS = 'tvdl/getListMemberSuccess'
export const GET_LIST_MEMBER_FAIL = 'tvdl/getListMemberFail'
export const DELETE_MEMBER = 'tvdl/deleteMember'
export const ADD_MEMBER = 'tvdl/addMember'
export const ADD_MEMBER_SUCCESS = 'tvdl/addMemberSuccess'
export const ADD_MEMBER_FAIL = 'tvdl/addMemberFail'
export const UPDATE_MEMBER = 'tvdl/updateMember'
export const UPDATE_MEMBER_SUCCESS = 'tvdl/updateMemberSuccess'
export const UPDATE_MEMBER_FAIL = 'tvdl/updateMemberFail'

export const GET_READER = 'tvdl/getReader'
export const GET_READER_SUCCESS = 'tvdl/getReaderSuccess'
export const GET_READER_FAIL = 'tvdl/getReaderFail'
export const GET_LIST_READER = 'tvdl/getListReader'
export const GET_LIST_READER_SUCCESS = 'tvdl/getListReaderSuccess'
export const GET_LIST_READER_FAIL = 'tvdl/getListReaderFail'
export const DELETE_READER = 'tvdl/deleteReader'
export const ADD_READER = 'tvdl/addReader'
export const ADD_READER_SUCCESS = 'tvdl/addReaderSuccess'
export const ADD_READER_FAIL = 'tvdl/addReaderFail'
export const UPDATE_READER = 'tvdl/updateReader'
export const UPDATE_READER_SUCCESS = 'tvdl/updateReaderSuccess'
export const UPDATE_READER_FAIL = 'tvdl/updateReaderFail'
