//Member
export const RESET = 'windsoft/reset'

export const GET_MEMBER = 'windsoft/getMember'
export const GET_MEMBER_SUCCESS = 'windsoft/getMemberSucces'
export const GET_MEMBER_FAIL = 'windsoft/getMemberFail'

export const GET_LIST_MEMBER = 'vitrans/getListMember'
export const GET_LIST_MEMBER_SUCCESS = 'vitrans/getListMemberSucces'
export const GET_LIST_MEMBER_FAIL = 'vitrans/getListMemberFail'
export const DELETE_MEMBER = 'vitrans/deleteMember'
export const ADD_MEMBER = 'vitrans/addMember'
export const ADD_MEMBER_SUCCESS = 'vitrans/addMemberSucces'
export const ADD_MEMBER_FAIL = 'vitrans/addMemberFail'
export const UPDATE_MEMBER = 'vitrans/updateMember'
export const UPDATE_MEMBER_SUCCESS = 'vitrans/updateMemberSucces'
export const UPDATE_MEMBER_FAIL = 'vitrans/updateMemberFail'

export const GET_LIST_TRANSPORT = 'vitrans/getListTransport'
export const GET_LIST_TRANSPORT_SUCCESS = 'vitrans/getListTransportSucces'
export const GET_LIST_TRANSPORT_FAIL = 'vitrans/getListTransportFail'
export const ADD_TRANSPORT = 'app/addTransport'
export const ADD_TRANSPORT_SUCCESS = 'app/addTransportSucces'
export const ADD_TRANSPORT_FAIL = 'app/addTransportFail'
export const UPDATE_TRANSPORT = 'app/updateTransport'
export const UPDATE_TRANSPORT_SUCCESS = 'app/updateTransportSucces'
export const UPDATE_TRANSPORT_FAIL = 'app/updateTransportFail'
export const DELETE_TRANSPORT = 'vitrans/deleteTransport'
